---
engines:
  duplication:
    exclude_paths:
      - "docs/**"
      - "spec/**/*"
exclude_paths:
  - "docs/**"
  - "spec/**/*"
  - ".github/**/*"
  - "babel.config.js"
  - "jest.config.js"
  - "jest.setup.js"
  - "jest.logger.js"
